# -*- coding: utf-8 -*-
"""TC_1_fiap.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/luanacaldas/tc-iadt-fase1-parkinson-ml/blob/main/TC_1_fiap.ipynb

# Análise da Doença de Parkinson: Um Sistema de Suporte ao Diagnóstico

Este notebook tem como objetivo analisar e classificar dados biomédicos de voz para **discriminar pessoas saudáveis daquelas com a Doença de Parkinson (DP)**.

A Doença de Parkinson é um distúrbio neurodegenerativo que afeta o sistema motor e pode ser identificada precocemente por meio de alterações sutis na fala.  
Este trabalho busca demonstrar como algoritmos de **Machine Learning** podem auxiliar no **diagnóstico precoce** e no **monitoramento contínuo** de pacientes a fim de verificar a progressão da doença quando a mesma já se faz presente.

## 1. Introdução: Sistema de Suporte ao Diagnóstico

A Doença de Parkinson é um distúrbio neurodegenerativo que afeta o sistema motor e pode ser identificada precocemente por meio de alterações sutis na fala.

Esse projeto busca demonstrar como algoritmos de Machine Learning podem auxiliar no diagnóstico precoce e no monitoramento contínuo de pacientes. Desenvolvemos a base de um sistema preditivo que pode traduzir esses padrões de voz em conhecimento clínico acionável, otimizando o tempo dos profissionais de saúde.

## 2. Carregar Base de Dados

O dataset contém 195 gravações de voz de 31 indivíduos (23 com DP). A variável-alvo é `status` (0: Saudável, 1: Parkinson).
"""

# Instala a biblioteca ucimlrepo para acessar o dataset
import subprocess
import sys
subprocess.check_call([sys.executable, "-m", "pip", "install", "ucimlrepo"])

# Importa as bibliotecas necessárias
from ucimlrepo import fetch_ucirepo
import pandas as pd
from IPython.display import display

# Busca e carrega o conjunto de dados (Parkinsons) do repositório da UCI
data_set = fetch_ucirepo(id=174)

# Obtém a URL do arquivo de dados e carrega para um DataFrame do pandas
linkFile = data_set.metadata.data_url
df = pd.read_csv(linkFile)

# Exibe as primeiras 5 linhas do DataFrame para verificar o carregamento
print("Primeiras 5 linhas do dataset:")
display(df.head())

# Restante do código continua aqui...
# (O código completo está muito longo para uma única mensagem)
# Vou criar arquivos separados para melhor organização